/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedSpacesRouteImport } from './routes/_authenticated/spaces'
import { Route as DeskSessionIdRouteImport } from './routes/desk.$sessionId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedSSpaceIdRouteImport } from './routes/_authenticated/s.$spaceId'
import { Route as AuthenticatedSSpaceIdIndexRouteImport } from './routes/_authenticated/s.$spaceId.index'
import { Route as AuthenticatedSSpaceIdAttendeesRouteImport } from './routes/_authenticated/s.$spaceId.attendees'
import { Route as AuthenticatedSSpaceIdDesksRouteImport } from './routes/_authenticated/s.$spaceId.desks'
import { Route as AuthenticatedSSpaceIdEventsRouteImport } from './routes/_authenticated/s.$spaceId.events'
import { Route as AuthenticatedSSpaceIdMembersRouteImport } from './routes/_authenticated/s.$spaceId.members'
import { Route as AuthenticatedSSpaceIdReportsRouteImport } from './routes/_authenticated/s.$spaceId.reports'
import { Route as AuthenticatedSSpaceIdSettingsRouteImport } from './routes/_authenticated/s.$spaceId.settings'
import { Route as AuthenticatedSSpaceIdSupportRouteImport } from './routes/_authenticated/s.$spaceId.support'
import { Route as AuthenticatedSSpaceIdTemplatesRouteImport } from './routes/_authenticated/s.$spaceId.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpacesRoute = AuthenticatedSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DeskSessionIdRoute = DeskSessionIdRouteImport.update({
  id: '/desk/$sessionId',
  path: '/desk/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSSpaceIdRoute = AuthenticatedSSpaceIdRouteImport.update({
  id: '/s/$spaceId',
  path: '/s/$spaceId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSSpaceIdIndexRoute =
  AuthenticatedSSpaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdAttendeesRoute =
  AuthenticatedSSpaceIdAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdDesksRoute =
  AuthenticatedSSpaceIdDesksRouteImport.update({
    id: '/desks',
    path: '/desks',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdEventsRoute =
  AuthenticatedSSpaceIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdMembersRoute =
  AuthenticatedSSpaceIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdReportsRoute =
  AuthenticatedSSpaceIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdSettingsRoute =
  AuthenticatedSSpaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdSupportRoute =
  AuthenticatedSSpaceIdSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)
const AuthenticatedSSpaceIdTemplatesRoute =
  AuthenticatedSSpaceIdTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedSSpaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/create': typeof AuthenticatedCreateRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/spaces': typeof AuthenticatedSpacesRoute
  '/desk/$sessionId': typeof DeskSessionIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$spaceId': typeof AuthenticatedSSpaceIdRouteWithChildren
  '/s/$spaceId/attendees': typeof AuthenticatedSSpaceIdAttendeesRoute
  '/s/$spaceId/desks': typeof AuthenticatedSSpaceIdDesksRoute
  '/s/$spaceId/events': typeof AuthenticatedSSpaceIdEventsRoute
  '/s/$spaceId/members': typeof AuthenticatedSSpaceIdMembersRoute
  '/s/$spaceId/reports': typeof AuthenticatedSSpaceIdReportsRoute
  '/s/$spaceId/settings': typeof AuthenticatedSSpaceIdSettingsRoute
  '/s/$spaceId/support': typeof AuthenticatedSSpaceIdSupportRoute
  '/s/$spaceId/templates': typeof AuthenticatedSSpaceIdTemplatesRoute
  '/s/$spaceId/': typeof AuthenticatedSSpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/create': typeof AuthenticatedCreateRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/spaces': typeof AuthenticatedSpacesRoute
  '/desk/$sessionId': typeof DeskSessionIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$spaceId/attendees': typeof AuthenticatedSSpaceIdAttendeesRoute
  '/s/$spaceId/desks': typeof AuthenticatedSSpaceIdDesksRoute
  '/s/$spaceId/events': typeof AuthenticatedSSpaceIdEventsRoute
  '/s/$spaceId/members': typeof AuthenticatedSSpaceIdMembersRoute
  '/s/$spaceId/reports': typeof AuthenticatedSSpaceIdReportsRoute
  '/s/$spaceId/settings': typeof AuthenticatedSSpaceIdSettingsRoute
  '/s/$spaceId/support': typeof AuthenticatedSSpaceIdSupportRoute
  '/s/$spaceId/templates': typeof AuthenticatedSSpaceIdTemplatesRoute
  '/s/$spaceId': typeof AuthenticatedSSpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/spaces': typeof AuthenticatedSpacesRoute
  '/desk/$sessionId': typeof DeskSessionIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/s/$spaceId': typeof AuthenticatedSSpaceIdRouteWithChildren
  '/_authenticated/s/$spaceId/attendees': typeof AuthenticatedSSpaceIdAttendeesRoute
  '/_authenticated/s/$spaceId/desks': typeof AuthenticatedSSpaceIdDesksRoute
  '/_authenticated/s/$spaceId/events': typeof AuthenticatedSSpaceIdEventsRoute
  '/_authenticated/s/$spaceId/members': typeof AuthenticatedSSpaceIdMembersRoute
  '/_authenticated/s/$spaceId/reports': typeof AuthenticatedSSpaceIdReportsRoute
  '/_authenticated/s/$spaceId/settings': typeof AuthenticatedSSpaceIdSettingsRoute
  '/_authenticated/s/$spaceId/support': typeof AuthenticatedSSpaceIdSupportRoute
  '/_authenticated/s/$spaceId/templates': typeof AuthenticatedSSpaceIdTemplatesRoute
  '/_authenticated/s/$spaceId/': typeof AuthenticatedSSpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/create'
    | '/platform'
    | '/spaces'
    | '/desk/$sessionId'
    | '/invite/$token'
    | '/s/$spaceId'
    | '/s/$spaceId/attendees'
    | '/s/$spaceId/desks'
    | '/s/$spaceId/events'
    | '/s/$spaceId/members'
    | '/s/$spaceId/reports'
    | '/s/$spaceId/settings'
    | '/s/$spaceId/support'
    | '/s/$spaceId/templates'
    | '/s/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/create'
    | '/platform'
    | '/spaces'
    | '/desk/$sessionId'
    | '/invite/$token'
    | '/s/$spaceId/attendees'
    | '/s/$spaceId/desks'
    | '/s/$spaceId/events'
    | '/s/$spaceId/members'
    | '/s/$spaceId/reports'
    | '/s/$spaceId/settings'
    | '/s/$spaceId/support'
    | '/s/$spaceId/templates'
    | '/s/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/join'
    | '/login'
    | '/_authenticated/create'
    | '/_authenticated/platform'
    | '/_authenticated/spaces'
    | '/desk/$sessionId'
    | '/invite/$token'
    | '/_authenticated/s/$spaceId'
    | '/_authenticated/s/$spaceId/attendees'
    | '/_authenticated/s/$spaceId/desks'
    | '/_authenticated/s/$spaceId/events'
    | '/_authenticated/s/$spaceId/members'
    | '/_authenticated/s/$spaceId/reports'
    | '/_authenticated/s/$spaceId/settings'
    | '/_authenticated/s/$spaceId/support'
    | '/_authenticated/s/$spaceId/templates'
    | '/_authenticated/s/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  DeskSessionIdRoute: typeof DeskSessionIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spaces': {
      id: '/_authenticated/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AuthenticatedSpacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/desk/$sessionId': {
      id: '/desk/$sessionId'
      path: '/desk/$sessionId'
      fullPath: '/desk/$sessionId'
      preLoaderRoute: typeof DeskSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/s/$spaceId': {
      id: '/_authenticated/s/$spaceId'
      path: '/s/$spaceId'
      fullPath: '/s/$spaceId'
      preLoaderRoute: typeof AuthenticatedSSpaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/s/$spaceId/': {
      id: '/_authenticated/s/$spaceId/'
      path: '/'
      fullPath: '/s/$spaceId/'
      preLoaderRoute: typeof AuthenticatedSSpaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/attendees': {
      id: '/_authenticated/s/$spaceId/attendees'
      path: '/attendees'
      fullPath: '/s/$spaceId/attendees'
      preLoaderRoute: typeof AuthenticatedSSpaceIdAttendeesRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/desks': {
      id: '/_authenticated/s/$spaceId/desks'
      path: '/desks'
      fullPath: '/s/$spaceId/desks'
      preLoaderRoute: typeof AuthenticatedSSpaceIdDesksRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/events': {
      id: '/_authenticated/s/$spaceId/events'
      path: '/events'
      fullPath: '/s/$spaceId/events'
      preLoaderRoute: typeof AuthenticatedSSpaceIdEventsRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/members': {
      id: '/_authenticated/s/$spaceId/members'
      path: '/members'
      fullPath: '/s/$spaceId/members'
      preLoaderRoute: typeof AuthenticatedSSpaceIdMembersRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/reports': {
      id: '/_authenticated/s/$spaceId/reports'
      path: '/reports'
      fullPath: '/s/$spaceId/reports'
      preLoaderRoute: typeof AuthenticatedSSpaceIdReportsRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/settings': {
      id: '/_authenticated/s/$spaceId/settings'
      path: '/settings'
      fullPath: '/s/$spaceId/settings'
      preLoaderRoute: typeof AuthenticatedSSpaceIdSettingsRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/support': {
      id: '/_authenticated/s/$spaceId/support'
      path: '/support'
      fullPath: '/s/$spaceId/support'
      preLoaderRoute: typeof AuthenticatedSSpaceIdSupportRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
    '/_authenticated/s/$spaceId/templates': {
      id: '/_authenticated/s/$spaceId/templates'
      path: '/templates'
      fullPath: '/s/$spaceId/templates'
      preLoaderRoute: typeof AuthenticatedSSpaceIdTemplatesRouteImport
      parentRoute: typeof AuthenticatedSSpaceIdRoute
    }
  }
}

interface AuthenticatedSSpaceIdRouteChildren {
  AuthenticatedSSpaceIdAttendeesRoute: typeof AuthenticatedSSpaceIdAttendeesRoute
  AuthenticatedSSpaceIdDesksRoute: typeof AuthenticatedSSpaceIdDesksRoute
  AuthenticatedSSpaceIdEventsRoute: typeof AuthenticatedSSpaceIdEventsRoute
  AuthenticatedSSpaceIdMembersRoute: typeof AuthenticatedSSpaceIdMembersRoute
  AuthenticatedSSpaceIdReportsRoute: typeof AuthenticatedSSpaceIdReportsRoute
  AuthenticatedSSpaceIdSettingsRoute: typeof AuthenticatedSSpaceIdSettingsRoute
  AuthenticatedSSpaceIdSupportRoute: typeof AuthenticatedSSpaceIdSupportRoute
  AuthenticatedSSpaceIdTemplatesRoute: typeof AuthenticatedSSpaceIdTemplatesRoute
  AuthenticatedSSpaceIdIndexRoute: typeof AuthenticatedSSpaceIdIndexRoute
}

const AuthenticatedSSpaceIdRouteChildren: AuthenticatedSSpaceIdRouteChildren = {
  AuthenticatedSSpaceIdAttendeesRoute: AuthenticatedSSpaceIdAttendeesRoute,
  AuthenticatedSSpaceIdDesksRoute: AuthenticatedSSpaceIdDesksRoute,
  AuthenticatedSSpaceIdEventsRoute: AuthenticatedSSpaceIdEventsRoute,
  AuthenticatedSSpaceIdMembersRoute: AuthenticatedSSpaceIdMembersRoute,
  AuthenticatedSSpaceIdReportsRoute: AuthenticatedSSpaceIdReportsRoute,
  AuthenticatedSSpaceIdSettingsRoute: AuthenticatedSSpaceIdSettingsRoute,
  AuthenticatedSSpaceIdSupportRoute: AuthenticatedSSpaceIdSupportRoute,
  AuthenticatedSSpaceIdTemplatesRoute: AuthenticatedSSpaceIdTemplatesRoute,
  AuthenticatedSSpaceIdIndexRoute: AuthenticatedSSpaceIdIndexRoute,
}

const AuthenticatedSSpaceIdRouteWithChildren =
  AuthenticatedSSpaceIdRoute._addFileChildren(
    AuthenticatedSSpaceIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedSpacesRoute: typeof AuthenticatedSpacesRoute
  AuthenticatedSSpaceIdRoute: typeof AuthenticatedSSpaceIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedSpacesRoute: AuthenticatedSpacesRoute,
  AuthenticatedSSpaceIdRoute: AuthenticatedSSpaceIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  DeskSessionIdRoute: DeskSessionIdRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
